// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from the workflow documents in
// .mboss/workflows/.

import type { ScheduleEntry, WorkflowEntry } from '../app/contract.js';

export const workflows: WorkflowEntry[] = [];

export const schedules: ScheduleEntry[] = [];
