import { mkdir, readFile, readdir, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import {
  mbossDirOf,
  withLock,
  workflowsDir,
  writeFileAtomic,
} from '../apply/index.js';
import {
  REGISTRY_FILE,
  registrySpecifier,
  workflowFilePath,
} from '../app-contract/index.js';
import { WorkflowIRSchema, type WorkflowIR } from '../ir/index.js';
import { loadOrScan, type LibManifest } from '../manifest/index.js';
import {
  canCompile,
  validateWorkflow,
  type Diagnostic,
} from '../validate/index.js';

import { emitWorkflow } from './emit-linear.js';
import { camelCase } from './names.js';
import { literal } from './predicate.js';
import { UnsupportedIR } from './unsupported.js';

/**
 * Turning a workflow document into the TypeScript
 * a generated project runs.
 *
 * The gate is validation's, not this module's:
 * `compileWorkflow` runs the same rules the canvas
 * and the MCP server run, and refuses whatever
 * `canCompile` refuses. A compiler with a second
 * opinion about what is legal is a compiler that
 * disagrees with the canvas somebody drew.
 */

export type CompileRequest = {
  ir: WorkflowIR;
  manifest: LibManifest;
  /** The zone stamped into a schedule descriptor
   *  when the trigger declares none. Required, and
   *  never read from the machine: a golden blessed
   *  on a laptop would fail in CI. */
  timezone: string;
};

export type CompileResult =
  | { ok: true; path: string; source: string }
  | { ok: false; reason: 'CANNOT_COMPILE'; diagnostics: Diagnostic[] }
  | { ok: false; reason: 'UNSUPPORTED'; nodeId?: string; message: string };

/**
 * Pure and synchronous: no clock, no filesystem,
 * no randomness. Two calls with the same inputs
 * produce the same bytes, which is what makes
 * "regeneration is clean" a property rather than a
 * hope.
 */
export function compileWorkflow(request: CompileRequest): CompileResult {
  const diagnostics = validateWorkflow(request.ir, {
    manifest: request.manifest,
  });

  if (!canCompile(request.ir, diagnostics)) {
    return { ok: false, reason: 'CANNOT_COMPILE', diagnostics };
  }

  try {
    return {
      ok: true,
      path: workflowFilePath(request.ir.name),
      source: emitWorkflow(request),
    };
  } catch (error) {
    if (!(error instanceof UnsupportedIR)) throw error;

    return {
      ok: false,
      reason: 'UNSUPPORTED',
      ...(error.nodeId === undefined ? {} : { nodeId: error.nodeId }),
      message: error.message,
    };
  }
}

/** One workflow, as the registry names it. */
export type RegistryEntry = {
  name: string;
  title: string;
  /** Scheduled workflows appear in both arrays:
   *  once so the ingress can name them, once so
   *  the boot can apply their schedule. */
  scheduled: boolean;
};

/**
 * `src/workflows/index.ts` — what the app's boot
 * imports to register everything.
 *
 * Takes more than the names because the file says
 * more than the names: a workflow's title is not
 * derivable from its slug, and whether it has a
 * schedule is a fact about its trigger.
 */
export function compileRegistry(entries: readonly RegistryEntry[]): string {
  const ordered = [...entries].sort((a, b) => (a.name < b.name ? -1 : 1));
  const lines: string[] = [
    '// GENERATED BY MBOSS — DO NOT EDIT.',
    '// Regenerated from the workflow documents in',
    '// .mboss/workflows/.',
    '',
    "import type { ScheduleEntry, WorkflowEntry } from '../app/contract.js';",
  ];

  for (const entry of ordered) {
    lines.push(
      `import * as ${camelCase(entry.name)} from ` +
        `'${registrySpecifier(entry.name)}';`,
    );
  }

  lines.push('');

  if (ordered.length === 0) {
    lines.push('export const workflows: WorkflowEntry[] = [];');
  } else {
    lines.push('export const workflows: WorkflowEntry[] = [');
    for (const entry of ordered) {
      const module = camelCase(entry.name);

      lines.push(
        '  {',
        `    name: '${entry.name}',`,
        `    title: ${literal(entry.title)},`,
        `    workflowFn: ${module}.${module},`,
        `    trigger: ${module}.trigger,`,
        `    checkPayload: ${module}.checkPayload,`,
        `    waits: ${module}.waits,`,
        `    eventWaits: ${module}.eventWaits,`,
        '  },',
      );
    }
    lines.push('];');
  }

  lines.push('');

  const scheduled = ordered.filter((entry) => entry.scheduled);

  if (scheduled.length === 0) {
    lines.push('export const schedules: ScheduleEntry[] = [];');
  } else {
    lines.push('export const schedules: ScheduleEntry[] = [');
    for (const entry of scheduled) {
      lines.push(`  ${camelCase(entry.name)}.schedule,`);
    }
    lines.push('];');
  }

  return `${lines.join('\n')}\n`;
}

export type CompileProjectOptions = { timezone: string };

export type CompileProjectResult =
  | { ok: true; written: string[]; removed: string[] }
  | { ok: false; failures: { name: string; result: CompileResult }[] };

/**
 * Compiles every applied workflow in a project and
 * writes `src/workflows/`.
 *
 * It prunes first. A workflow that has been
 * renamed or deleted leaves a generated file that
 * the new registry no longer imports but that the
 * project's `tsconfig` still type-checks — against
 * handlers that may have gone with it. The gate
 * then fails on a file nobody is allowed to edit,
 * and it fails on the run after the change rather
 * than the one that caused it.
 *
 * It takes the project lock itself, and it never
 * runs inside another one: `applySpec` takes and
 * releases its own, and the lock is not reentrant.
 */
export async function compileProject(
  projectDir: string,
  opts: CompileProjectOptions,
): Promise<CompileProjectResult> {
  const mbossDir = mbossDirOf(projectDir);

  return await withLock(mbossDir, async () => {
    const manifest = loadOrScan(projectDir);
    const documents = await readDocuments(mbossDir);
    const failures: { name: string; result: CompileResult }[] = [];
    const sources = new Map<string, string>();
    const entries: RegistryEntry[] = [];

    for (const ir of documents) {
      const result = compileWorkflow({ ir, manifest, timezone: opts.timezone });

      if (!result.ok) {
        failures.push({ name: ir.name, result });
        continue;
      }

      sources.set(result.path, result.source);
      entries.push({
        name: ir.name,
        title: ir.title ?? ir.name,
        scheduled: hasSchedule(ir),
      });
    }

    if (failures.length > 0) return { ok: false, failures };

    const removed = await prune(projectDir, new Set(sources.keys()));

    sources.set(REGISTRY_FILE, compileRegistry(entries));

    const written = [...sources.keys()].sort();
    for (const path of written) {
      await write(projectDir, path, sources.get(path) ?? '');
    }

    return { ok: true, written, removed };
  });
}

/** Whether a workflow's trigger fires on a clock. */
function hasSchedule(ir: WorkflowIR): boolean {
  return ir.nodes.some(
    (node) => node.kind === 'trigger' && node.config.mode === 'schedule',
  );
}

async function readDocuments(mbossDir: string): Promise<WorkflowIR[]> {
  const dir = workflowsDir(mbossDir);
  let names: string[];

  try {
    names = await readdir(dir);
  } catch {
    return [];
  }

  const documents: WorkflowIR[] = [];

  for (const name of names.sort()) {
    if (!name.endsWith('.workflow.json')) continue;

    const text = await readFile(join(dir, name), 'utf8');
    documents.push(WorkflowIRSchema.parse(JSON.parse(text)));
  }

  return documents;
}

async function write(
  projectDir: string,
  relative: string,
  contents: string,
): Promise<void> {
  const path = join(projectDir, relative);

  await mkdir(dirname(path), { recursive: true });
  await writeFileAtomic(path, contents);
}

/**
 * Deletes the generated workflow files no document
 * accounts for. Only `*.workflow.ts`, and only
 * inside the generated directory: the registry is
 * rewritten rather than removed, and nothing else
 * in the project is this function's business.
 */
async function prune(
  projectDir: string,
  keep: ReadonlySet<string>,
): Promise<string[]> {
  const dir = join(projectDir, 'src', 'workflows');
  let names: string[];

  try {
    names = await readdir(dir);
  } catch {
    return [];
  }

  const removed: string[] = [];

  for (const name of names.sort()) {
    if (!name.endsWith('.workflow.ts')) continue;

    const path = `src/workflows/${name}`;
    if (keep.has(path)) continue;

    await rm(join(projectDir, path), { force: true });
    removed.push(path);
  }

  return removed;
}
