// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/checkout.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { chargeCard } from '../../lib/chargeCard.js';
import type { OrderPlaced } from '../../lib/checkoutTypes.js';
import { fulfillOrder } from '../../lib/fulfillOrder.js';
import { releaseStock } from '../../lib/releaseStock.js';
import { reserveStock } from '../../lib/reserveStock.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';

async function checkoutFn(evt: OrderPlaced): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error('checkout: no workflow id — not running as a workflow.');
  }

  const requesterEmail = evt.customer?.email;

  const reserveStockOut = await appDb.runTransaction(
    async () => reserveStock(evt),
    { name: 'reserve_stock' },
  );

  // External service: payments.
  const chargeCardOut = await DBOS.runStep(
    async () => chargeCard(reserveStockOut),
    {
      name: 'charge_card',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  if (chargeCardOut.status === 'captured') {
    const fulfillOut = await DBOS.runStep(
      async () => fulfillOrder(chargeCardOut),
      {
        name: 'fulfill',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Checkout',
          nodeId: 'confirm',
          to: requesterEmail,
          subject: 'Your order is on its way',
          bodyMarkdown:
            'We have taken payment and your order is being packed. You will ' +
            'hear from us again when it ships.',
          attach: { kind: 'none' },
          downstream: [],
        }),
      {
        name: 'confirm',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );

    return;
  }

  const releaseStockOut = await appDb.runTransaction(
    async () => releaseStock(chargeCardOut),
    { name: 'release_stock' },
  );

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Checkout',
        nodeId: 'decline',
        to: requesterEmail,
        subject: 'We could not take payment',
        bodyMarkdown:
          'Your card was declined, so nothing was charged and the items are ' +
          'back in stock. Try again whenever you like.',
        attach: { kind: 'none' },
        downstream: [],
      }),
    {
      name: 'decline',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );

  return;
}

export const checkout = DBOS.registerWorkflow(checkoutFn, { name: 'checkout' });

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'order.placed',
  idempotencyKeyPath: 'orderId',
  requesterEmailPath: 'customer.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<OrderPlaced>;
  const key = event.orderId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'orderId is missing' };
  }
  const requesterEmail = event.customer?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'customer.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
