// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/deep_research.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import type { Evidence, ResearchBrief } from '../../lib/deepResearchTypes.js';
import { enoughEvidence } from '../../lib/enoughEvidence.js';
import { searchSources } from '../../lib/searchSources.js';
import { writeReport } from '../../lib/writeReport.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function deepResearchFn(evt: ResearchBrief): Promise<void> {
  let round = 0;
  let searchCarried: Evidence | undefined;

  do {
    round += 1;

    const searchOut = await DBOS.runStep(async () => searchSources(evt), {
      name: `search.r${round}`,
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
    searchCarried = searchOut;

    const enoughDecision = await DBOS.runStep(
      async () => enoughEvidence(searchOut),
      {
        name: `enough.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (enoughDecision === false) {
      continue;
    }

    if (enoughDecision === true) {
      break;
    }

    return;
  } while (round < 6);

  if (searchCarried === undefined) {
    // Unreachable: every way out of the loop has
    // already assigned this. The check is here
    // because the type says so and a cast would
    // be a lie about which of the two is
    // authoritative.
    throw new Error('deep_research: search produced no result.');
  }

  const writeReportOut = await DBOS.runStep(
    async () => writeReport(searchCarried),
    {
      name: 'write_report',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const deepResearch = DBOS.registerWorkflow(deepResearchFn, {
  name: 'deep_research',
});

export const trigger: TriggerDescriptor = { mode: 'manual' };

export function checkPayload(): PayloadCheck {
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
