// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/deployment.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { buildRelease } from '../../lib/buildRelease.js';
import { checkHealth } from '../../lib/checkHealth.js';
import { deployBuild } from '../../lib/deployBuild.js';
import type { ReleaseRequest } from '../../lib/deploymentTypes.js';
import { rollBack } from '../../lib/rollBack.js';
import type {
  ApprovalReply,
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function deploymentFn(evt: ReleaseRequest): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error('deployment: no workflow id — not running as a workflow.');
  }

  const buildOut = await DBOS.runStep(async () => buildRelease(evt), {
    name: 'build',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Deployment',
        nodeId: 'approve_release',
        to: 'releases@example.com',
        subject: 'Ship this release?',
        bodyMarkdown:
          'A build is waiting to go out. Open the link to ship it or hold it ' +
          'back.',
        attach: {
          kind: 'approval',
          nodeId: 'approve_release',
          expiresInSeconds: 172800,
        },
        downstream: [
          'Deploy',
          'Let it settle',
          'Check health',
          'Announce the release',
          'Roll back',
          'Announce the rollback',
        ],
      }),
    {
      name: 'approve_release.ask',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );

  await DBOS.runStep(
    async () =>
      registerWaitCorrelation({
        runId,
        nodeId: 'approve_release',
        topic: 'mboss.form',
        key: 'approve_release',
      }),
    {
      name: 'approve_release.register',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  // recv answers a timeout with null and never
  // throws, so this is a check and not a catch.
  // 2 days, as seconds.
  const approveReleaseOut = await DBOS.recv<ApprovalReply>('approve_release', {
    timeoutSeconds: 172800,
  });

  await DBOS.runStep(
    async () => clearWaitCorrelation(runId, 'approve_release'),
    {
      name: 'approve_release.clear',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  if (approveReleaseOut === null) {
    throw new Error('approve_release: nobody answered within 2 days.');
  }

  if (approveReleaseOut.approved === true) {
    const deployOut = await DBOS.runStep(async () => deployBuild(buildOut), {
      name: 'deploy',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });

    // Durable: the wake-up time is written to the
    // database, so the wait survives a restart.
    // 300 seconds, as milliseconds.
    await DBOS.sleep(300000);

    const checkHealthOut = await DBOS.runStep(
      async () => checkHealth(deployOut),
      {
        name: 'check_health',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (checkHealthOut.healthy === true) {
      // A retry can send a second copy when the
      // provider accepted a request whose
      // response was lost. A run that never sends
      // its only link sleeps until its timeout,
      // which is worse.
      await DBOS.runStep(
        async () =>
          sendNodeEmail({
            runId,
            workflowTitle: 'Deployment',
            nodeId: 'announce',
            to: 'releases@example.com',
            subject: 'The release is live',
            bodyMarkdown: 'The new version is deployed and reporting healthy.',
            attach: { kind: 'none' },
            downstream: [],
          }),
        {
          name: 'announce',
          retriesAllowed: true,
          maxAttempts: 3,
          intervalSeconds: 1,
          backoffRate: 2,
          shouldRetry: isTransientSendFailure,
        },
      );

      return;
    }

    const rollBackOut = await DBOS.runStep(
      async () => rollBack(checkHealthOut),
      {
        name: 'roll_back',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Deployment',
          nodeId: 'announce_rollback',
          to: 'releases@example.com',
          subject: 'The release was rolled back',
          bodyMarkdown:
            'The new version came up unhealthy, so the previous one is ' +
            'serving again.',
          attach: { kind: 'none' },
          downstream: [],
        }),
      {
        name: 'announce_rollback',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );

    return;
  }

  return;
}

export const deployment = DBOS.registerWorkflow(deploymentFn, {
  name: 'deployment',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'release.requested',
  idempotencyKeyPath: 'releaseId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<ReleaseRequest>;
  const key = event.releaseId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'releaseId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {
  approve_release: {
    nodeId: 'approve_release',
    title: 'Approve release',
    page: 'approval',
    fields: [],
    downstream: [
      'Deploy',
      'Let it settle',
      'Check health',
      'Announce the release',
      'Roll back',
      'Announce the rollback',
    ],
  },
};

export const eventWaits: EventWait[] = [];
