// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/document_ingestion.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import type {
  EmbeddedPage,
  UploadEvent,
} from '../../lib/documentIngestionTypes.js';
import { embedPage } from '../../lib/embedPage.js';
import { finalizeIngestion } from '../../lib/finalizeIngestion.js';
import { parsePages } from '../../lib/parsePages.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';

async function documentIngestionFn(evt: UploadEvent): Promise<void> {
  const parsePagesOut = await DBOS.runStep(async () => parsePages(evt), {
    name: 'parse_pages',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  // allSettled rather than all: one rejection
  // must not take the process down before the
  // others have checkpointed.
  const items = parsePagesOut.pages;
  const settled: PromiseSettledResult<EmbeddedPage>[] = [];
  for (let offset = 0; offset < items.length; offset += 4) {
    const chunk = items.slice(offset, offset + 4);
    const settledChunk = await Promise.allSettled(
      chunk.map((item, index) =>
        DBOS.runStep(async () => embedPage(item), {
          name: `embed_page[${offset + index}]`,
          retriesAllowed: true,
          maxAttempts: 3,
          intervalSeconds: 1,
          backoffRate: 2,
        }),
      ),
    );
    settled.push(...settledChunk);
  }

  const failed = settled.filter((r) => r.status === 'rejected');
  if (failed.length > 0) {
    throw new Error(
      `embed_page: ${failed.length} of ${settled.length} items failed`,
    );
  }

  const embedPageOut = settled.flatMap((r) =>
    r.status === 'fulfilled' ? [r.value] : [],
  );

  const finalizeOut = await appDb.runTransaction(
    async () => finalizeIngestion(embedPageOut),
    { name: 'finalize' },
  );
}

export const documentIngestion = DBOS.registerWorkflow(documentIngestionFn, {
  name: 'document_ingestion',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'document.uploaded',
  idempotencyKeyPath: 'uploadId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<UploadEvent>;
  const key = event.uploadId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'uploadId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
