// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/document_ingestion_queued.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';
import type { WorkflowHandle } from '@dbos-inc/dbos-sdk';

import type {
  DocumentUploaded,
  IndexResult,
  Page,
} from '../../lib/documentIngestionQueuedTypes.js';
import { downloadDocument } from '../../lib/downloadDocument.js';
import { indexPage } from '../../lib/indexPage.js';
import { markIngested } from '../../lib/markIngested.js';
import { parsePdf } from '../../lib/parsePdf.js';
import type {
  EventWait,
  PayloadCheck,
  QueueEntry,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { queueKey } from '../app/queues.js';

async function indexPagesQueuedFn(item: Page): Promise<IndexResult> {
  return await DBOS.runStep(async () => indexPage(item), {
    name: 'index_pages',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

const indexPagesQueued = DBOS.registerWorkflow(indexPagesQueuedFn, {
  name: 'index_pages.queued.document_ingestion_queued',
});

async function documentIngestionQueuedFn(evt: DocumentUploaded): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'document_ingestion_queued: no workflow id — not running as a workflow.',
    );
  }

  const requesterEmail = evt.requestedBy;

  const downloadPdfOut = await DBOS.runStep(async () => downloadDocument(evt), {
    name: 'download_pdf',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  const parsePagesOut = await DBOS.runStep(
    async () => parsePdf(downloadPdfOut),
    {
      name: 'parse_pages',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  const items = parsePagesOut.pages;
  const handles: WorkflowHandle<IndexResult>[] = [];
  // An item whose key a run already in flight
  // holds joins that run instead of starting a
  // second, so its place in the list below holds
  // the result of that run.
  for (const item of items) {
    handles.push(
      await DBOS.startWorkflow(indexPagesQueued, {
        queueName: 'document-index',
        enqueueOptions: {
          deduplicationID: queueKey(
            'index_pages',
            'documentId',
            item.documentId,
          ),
        },
        duplicationPolicy: 'return-existing',
      })(item),
    );
  }

  const settled: PromiseSettledResult<IndexResult>[] = [];
  // One at a time rather than through allSettled:
  // one poll loop starts them all, waiting in the
  // order they were enqueued numbers the rows the
  // same way on every run, and the queue holds
  // them back either way.
  for (const handle of handles) {
    try {
      settled.push({ status: 'fulfilled', value: await handle.getResult() });
    } catch (reason) {
      settled.push({ status: 'rejected', reason });
    }
  }

  const failed = settled.filter((r) => r.status === 'rejected');
  if (failed.length > 0) {
    throw new Error(
      `index_pages: ${failed.length} of ${settled.length} items failed`,
    );
  }

  const indexPagesOut = settled.flatMap((r) =>
    r.status === 'fulfilled' ? [r.value] : [],
  );

  const finalizeDocumentOut = await appDb.runTransaction(
    async () => markIngested(indexPagesOut),
    { name: 'finalize_document' },
  );

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Document ingestion on a queue',
        nodeId: 'notify_caller',
        to: requesterEmail,
        subject: 'Your document is indexed',
        bodyMarkdown:
          'Every page of the document you uploaded has been indexed, and it ' +
          'is ready to search.',
        attach: { kind: 'none' },
        downstream: [],
      }),
    {
      name: 'notify_caller',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );
}

export const documentIngestionQueued = DBOS.registerWorkflow(
  documentIngestionQueuedFn,
  {
    name: 'document_ingestion_queued',
  },
);

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'document.uploaded',
  idempotencyKeyPath: 'documentId',
  requesterEmailPath: 'requestedBy',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<DocumentUploaded>;
  const key = event.documentId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'documentId is missing' };
  }
  const requesterEmail = event.requestedBy;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'requestedBy is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];

export const queues: QueueEntry[] = [
  {
    name: 'document-index',
    options: {
      globalConcurrency: 8,
      workerConcurrency: 2,
      rateLimit: { limitPerPeriod: 100, periodSec: 60 },
    },
  },
];
