// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/human_approval.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { draftAnswer } from '../../lib/draftAnswer.js';
import type { QuestionAsked } from '../../lib/humanApprovalTypes.js';
import type {
  ApprovalReply,
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function humanApprovalFn(evt: QuestionAsked): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'human_approval: no workflow id — not running as a workflow.',
    );
  }

  const requesterEmail = evt.asker?.email;

  const draftAnswerOut = await DBOS.runStep(async () => draftAnswer(evt), {
    name: 'draft_answer',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Human approval',
        nodeId: 'sign_off',
        to: 'reviews@example.com',
        subject: 'Ready to send this answer?',
        bodyMarkdown:
          'An answer is waiting to go out. Open the link to send it or hold ' +
          'it back.',
        attach: {
          kind: 'approval',
          nodeId: 'sign_off',
          expiresInSeconds: 259200,
        },
        downstream: ['Send answer'],
      }),
    {
      name: 'sign_off.ask',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );

  await DBOS.runStep(
    async () =>
      registerWaitCorrelation({
        runId,
        nodeId: 'sign_off',
        topic: 'mboss.form',
        key: 'sign_off',
      }),
    {
      name: 'sign_off.register',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  // recv answers a timeout with null and never
  // throws, so this is a check and not a catch.
  // 3 days, as seconds.
  const signOffOut = await DBOS.recv<ApprovalReply>('sign_off', {
    timeoutSeconds: 259200,
  });

  await DBOS.runStep(async () => clearWaitCorrelation(runId, 'sign_off'), {
    name: 'sign_off.clear',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (signOffOut === null) {
    throw new Error('sign_off: nobody answered within 3 days.');
  }

  if (signOffOut.approved === true) {
    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Human approval',
          nodeId: 'send_answer',
          to: requesterEmail,
          subject: 'Your answer',
          bodyMarkdown:
            'Your question has been answered, and a person read the answer ' +
            'over before this went out.',
          attach: { kind: 'none' },
          downstream: [],
        }),
      {
        name: 'send_answer',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );

    return;
  }

  return;
}

export const humanApproval = DBOS.registerWorkflow(humanApprovalFn, {
  name: 'human_approval',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'question.asked',
  idempotencyKeyPath: 'requestId',
  requesterEmailPath: 'asker.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<QuestionAsked>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  const requesterEmail = event.asker?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'asker.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {
  sign_off: {
    nodeId: 'sign_off',
    title: 'Sign off',
    page: 'approval',
    fields: [],
    downstream: ['Send answer'],
  },
};

export const eventWaits: EventWait[] = [];
