// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/refund_approval.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { getPurchase } from '../../lib/getPurchase.js';
import { markRefunded } from '../../lib/markRefunded.js';
import type { RefundRequest } from '../../lib/refundApprovalTypes.js';
import { refundPayment } from '../../lib/refundPayment.js';
import { refundPolicy } from '../../lib/refundPolicy.js';
import type {
  ApprovalReply,
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function refundApprovalFn(evt: RefundRequest): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'refund_approval: no workflow id — not running as a workflow.',
    );
  }

  const requesterEmail = evt.customer?.email;

  const loadPurchaseOut = await DBOS.runStep(async () => getPurchase(evt), {
    name: 'load_purchase',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  const evaluateRefundDecision = await DBOS.runStep(
    async () => refundPolicy(loadPurchaseOut),
    {
      name: 'evaluate_refund',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  if (evaluateRefundDecision === 'auto_approve') {
    // Nothing of its own to do on this way out.
  } else if (evaluateRefundDecision === 'review') {
    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Refund approval',
          nodeId: 'request_approval',
          to: 'support@example.com',
          subject: 'Approve this refund?',
          bodyMarkdown:
            'A refund needs a decision. Open the link to approve or reject ' +
            'it.',
          attach: {
            kind: 'approval',
            nodeId: 'request_approval',
            expiresInSeconds: 604800,
          },
          downstream: ['Refund payment', 'Update order', 'Email customer'],
        }),
      {
        name: 'request_approval.ask',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );

    await DBOS.runStep(
      async () =>
        registerWaitCorrelation({
          runId,
          nodeId: 'request_approval',
          topic: 'mboss.form',
          key: 'request_approval',
        }),
      {
        name: 'request_approval.register',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    // recv answers a timeout with null and never
    // throws, so this is a check and not a catch.
    // 7 days, as seconds.
    const requestApprovalOut = await DBOS.recv<ApprovalReply>(
      'request_approval',
      {
        timeoutSeconds: 604800,
      },
    );

    await DBOS.runStep(
      async () => clearWaitCorrelation(runId, 'request_approval'),
      {
        name: 'request_approval.clear',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (requestApprovalOut === null) {
      throw new Error('request_approval: nobody answered within 7 days.');
    }

    if (requestApprovalOut.approved === true) {
      // Nothing of its own to do on this way out.
    } else {
      // A retry can send a second copy when the
      // provider accepted a request whose
      // response was lost. A run that never sends
      // its only link sleeps until its timeout,
      // which is worse.
      await DBOS.runStep(
        async () =>
          sendNodeEmail({
            runId,
            workflowTitle: 'Refund approval',
            nodeId: 'email_denial',
            to: requesterEmail,
            subject: 'About your refund request',
            bodyMarkdown:
              'We looked at your request and could not approve it. Reply to ' +
              'this email if you have questions.',
            attach: { kind: 'none' },
            downstream: [],
          }),
        {
          name: 'email_denial',
          retriesAllowed: true,
          maxAttempts: 3,
          intervalSeconds: 1,
          backoffRate: 2,
          shouldRetry: isTransientSendFailure,
        },
      );

      return;
    }
  } else {
    return;
  }

  // External service: payments.
  const refundPaymentOut = await DBOS.runStep(
    async () => refundPayment(loadPurchaseOut),
    {
      name: 'refund_payment',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  const updateOrderOut = await appDb.runTransaction(
    async () => markRefunded(refundPaymentOut),
    { name: 'update_order' },
  );

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Refund approval',
        nodeId: 'email_customer',
        to: requesterEmail,
        subject: 'Your refund is on its way',
        bodyMarkdown:
          'We have refunded your order. The amount will reach your original ' +
          'payment method in a few days.',
        attach: { kind: 'none' },
        downstream: [],
      }),
    {
      name: 'email_customer',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );
}

export const refundApproval = DBOS.registerWorkflow(refundApprovalFn, {
  name: 'refund_approval',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'refund.requested',
  idempotencyKeyPath: 'refundId',
  requesterEmailPath: 'customer.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<RefundRequest>;
  const key = event.refundId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'refundId is missing' };
  }
  const requesterEmail = event.customer?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'customer.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {
  request_approval: {
    nodeId: 'request_approval',
    title: 'Request approval',
    page: 'approval',
    fields: [],
    downstream: ['Refund payment', 'Update order', 'Email customer'],
  },
};

export const eventWaits: EventWait[] = [];
