// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/reliable_webhook.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { acknowledgeDelivery } from '../../lib/acknowledgeDelivery.js';
import { applyEvent } from '../../lib/applyEvent.js';
import type { WebhookDelivery } from '../../lib/reliableWebhookTypes.js';
import { verifySignature } from '../../lib/verifySignature.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';

async function reliableWebhookFn(evt: WebhookDelivery): Promise<void> {
  const verifyOut = await DBOS.runStep(async () => verifySignature(evt), {
    name: 'verify',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  const applyEventOut = await appDb.runTransaction(
    async () => applyEvent(verifyOut),
    { name: 'apply_event' },
  );

  // External service: event source.
  const acknowledgeOut = await DBOS.runStep(
    async () => acknowledgeDelivery(applyEventOut),
    {
      name: 'acknowledge',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const reliableWebhook = DBOS.registerWorkflow(reliableWebhookFn, {
  name: 'reliable_webhook',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'webhook.received',
  idempotencyKeyPath: 'deliveryId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookDelivery>;
  const key = event.deliveryId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'deliveryId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
