// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/scheduled_ops.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { listWork } from '../../lib/listWork.js';
import { processItem } from '../../lib/processItem.js';
import type { WorkResult } from '../../lib/scheduledOpsTypes.js';
import type {
  EventWait,
  PayloadCheck,
  ScheduleEntry,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';

async function scheduledOpsFn(
  scheduledTime: Date,
  context: unknown,
): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'scheduled_ops: no workflow id — not running as a workflow.',
    );
  }

  const listWorkOut = await DBOS.runStep(async () => listWork(), {
    name: 'list_work',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  // allSettled rather than all: one rejection
  // must not take the process down before the
  // others have checkpointed.
  const items = listWorkOut.items;
  const settled: PromiseSettledResult<WorkResult>[] = [];
  for (let offset = 0; offset < items.length; offset += 4) {
    const chunk = items.slice(offset, offset + 4);
    const settledChunk = await Promise.allSettled(
      chunk.map((item, index) =>
        appDb.runTransaction(async () => processItem(item), {
          name: `process_each[${offset + index}]`,
        }),
      ),
    );
    settled.push(...settledChunk);
  }

  const failed = settled.filter((r) => r.status === 'rejected');
  if (failed.length > 0) {
    throw new Error(
      `process_each: ${failed.length} of ${settled.length} items failed`,
    );
  }

  const processEachOut = settled.flatMap((r) =>
    r.status === 'fulfilled' ? [r.value] : [],
  );

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Scheduled operations',
        nodeId: 'report',
        to: 'ops@example.com',
        subject: 'The hourly sweep has finished',
        bodyMarkdown:
          'Every job that was due has been processed. Open the run in mBoss ' +
          'to see what it did.',
        attach: { kind: 'none' },
        downstream: [],
      }),
    {
      name: 'report',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );
}

export const scheduledOps = DBOS.registerWorkflow(scheduledOpsFn, {
  name: 'scheduled_ops',
});

export const trigger: TriggerDescriptor = { mode: 'schedule' };

export function checkPayload(): PayloadCheck {
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const schedule: ScheduleEntry = {
  scheduleName: 'scheduled_ops',
  workflowFn: scheduledOps,
  schedule: '0 * * * *',
  cronTimezone: 'UTC',
  automaticBackfill: true,
};

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
