// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/api_call.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { findSlot } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import { twilioChat } from '../../lib/twilioChat.js';
import type { WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function apiCallFn(evt: WebhookEvent): Promise<void> {
  // External service: stripe.
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  // External service: stripe.
  const findSlotOut = await DBOS.runStep(
    async () => findSlot(parseRequestOut),
    {
      name: 'find_slot',
      retriesAllowed: true,
      maxAttempts: 5,
      intervalSeconds: 2,
      backoffRate: 3,
    },
  );

  // External service: stripe.
  const twilioChatOut = await DBOS.runStep(
    async () => twilioChat(findSlotOut),
    {
      name: 'twilio_chat',
      retriesAllowed: false,
    },
  );
}

export const apiCall = DBOS.registerWorkflow(apiCallFn, { name: 'api_call' });

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
