// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/approval_flow.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { closeClaim, fileRefusal, payClaim } from '../../lib/expense.js';
import type { ExpenseClaim } from '../../lib/expense.js';
import type {
  ApprovalReply,
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function approvalFlowFn(evt: ExpenseClaim): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'approval_flow: no workflow id — not running as a workflow.',
    );
  }

  const requesterEmail = evt.submitter?.email;

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Expense approval',
        nodeId: 'manager_ok',
        to: 'ops@example.com',
        subject: 'Approve this expense',
        bodyMarkdown: 'Please take a look when you can.',
        attach: {
          kind: 'approval',
          nodeId: 'manager_ok',
          expiresInSeconds: 345600,
        },
        downstream: ['Close the claim'],
      }),
    {
      name: 'manager_ok.ask',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );

  await DBOS.runStep(
    async () =>
      registerWaitCorrelation({
        runId,
        nodeId: 'manager_ok',
        topic: 'mboss.form',
        key: 'manager_ok',
      }),
    {
      name: 'manager_ok.register',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  // recv answers a timeout with null and never
  // throws, so this is a check and not a catch.
  // 4 days, as seconds.
  const managerOkOut = await DBOS.recv<ApprovalReply>('manager_ok', {
    timeoutSeconds: 345600,
  });

  await DBOS.runStep(async () => clearWaitCorrelation(runId, 'manager_ok'), {
    name: 'manager_ok.clear',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (managerOkOut === null) {
    throw new Error('manager_ok: nobody answered within 4 days.');
  }

  if (managerOkOut.approved === true) {
    const payClaimOut = await DBOS.runStep(async () => payClaim(evt), {
      name: 'pay_claim',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });

    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Expense approval',
          nodeId: 'send_receipt',
          to: requesterEmail,
          subject: 'Your expense was paid',
          bodyMarkdown: 'The receipt is attached below.',
          attach: {
            kind: 'artifact',
            key: payClaimOut.receiptKey,
            expiresInSeconds: 604800,
          },
          downstream: [],
        }),
      {
        name: 'send_receipt',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );
  } else {
    const fileRefusalOut = await DBOS.runStep(async () => fileRefusal(evt), {
      name: 'file_refusal',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
  }

  const closeClaimOut = await DBOS.runStep(async () => closeClaim(), {
    name: 'close_claim',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const approvalFlow = DBOS.registerWorkflow(approvalFlowFn, {
  name: 'approval_flow',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'expense.filed',
  idempotencyKeyPath: 'claimId',
  requesterEmailPath: 'submitter.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<ExpenseClaim>;
  const key = event.claimId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'claimId is missing' };
  }
  const requesterEmail = event.submitter?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'submitter.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {
  manager_ok: {
    nodeId: 'manager_ok',
    title: 'Manager decides',
    page: 'approval',
    fields: [],
    downstream: ['Close the claim'],
  },
};

export const eventWaits: EventWait[] = [];
