// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/branch_three_ways.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { bookAppointment } from '../../lib/bookAppointment.js';
import { findSlot } from '../../lib/findSlot.js';
import { sweepStale } from '../../lib/sweepStale.js';
import { twilioChat } from '../../lib/twilioChat.js';
import type { BookingReq } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function branchThreeWaysFn(evt: BookingReq): Promise<void> {
  const findSlotOut = await DBOS.runStep(async () => findSlot(evt), {
    name: 'find_slot',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (findSlotOut.requestedSlotFree === true) {
    const bookNowOut = await DBOS.runStep(
      async () => bookAppointment(findSlotOut),
      {
        name: 'book_now',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
  } else if ((findSlotOut.alternatives?.length ?? 0) > 0) {
    const offerTimesOut = await DBOS.runStep(
      async () => twilioChat(findSlotOut),
      {
        name: 'offer_times',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
  } else if ((findSlotOut.requestedAt?.length ?? 0) > 0) {
    const sweepOldOut = await DBOS.runStep(async () => sweepStale(), {
      name: 'sweep_old',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
  } else {
    return;
  }

  const wrapUpOut = await DBOS.runStep(async () => sweepStale(), {
    name: 'wrap_up',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const branchThreeWays = DBOS.registerWorkflow(branchThreeWaysFn, {
  name: 'branch_three_ways',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
