// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/chat_retry_continue.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { bookAppointment } from '../../lib/bookAppointment.js';
import { findSlot } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import { readReply } from '../../lib/readReply.js';
import { recordBooking } from '../../lib/recordBooking.js';
import { twilioChat } from '../../lib/twilioChat.js';
import type { SlotGrid, WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';

async function chatRetryContinueFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  let round = 0;
  let findSlotCarried: SlotGrid | undefined;

  do {
    round += 1;

    const findSlotOut = await DBOS.runStep(
      async () => findSlot(parseRequestOut),
      {
        name: `find_slot.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
    findSlotCarried = findSlotOut;

    if (findSlotOut.requestedSlotFree === true) {
      break;
    }

    const twilioChatOut = await DBOS.runStep(
      async () => twilioChat(findSlotOut),
      {
        name: `twilio_chat.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    const readReplyOut = await DBOS.runStep(
      async () => readReply(twilioChatOut),
      {
        name: `read_reply.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (round < 10 && readReplyOut.intent === 'reschedule') {
      continue;
    }

    if (readReplyOut.intent === 'book') {
      break;
    }

    return;
  } while (round < 10);

  if (findSlotCarried === undefined) {
    // Unreachable: every way out of the loop has
    // already assigned this. The check is here
    // because the type says so and a cast would
    // be a lie about which of the two is
    // authoritative.
    throw new Error('chat_retry_continue: find_slot produced no result.');
  }

  const bookAppointmentOut = await DBOS.runStep(
    async () => bookAppointment(findSlotCarried),
    {
      name: 'book_appointment',
      retriesAllowed: true,
      maxAttempts: 2,
      intervalSeconds: 2,
      backoffRate: 2,
    },
  );

  const recordBookingOut = await appDb.runTransaction(
    async () => recordBooking(bookAppointmentOut),
    { name: 'record_booking' },
  );
}

export const chatRetryContinue = DBOS.registerWorkflow(chatRetryContinueFn, {
  name: 'chat_retry_continue',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
  idempotencyKeyPath: 'requestId',
  requesterEmailPath: 'customer.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookEvent>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  const requesterEmail = event.customer?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'customer.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
