// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/decision_yes_no.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import {
  autoApprove,
  closeClaim,
  fileRefusal,
  payClaim,
} from '../../lib/expense.js';
import type { ExpenseClaim } from '../../lib/expense.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function decisionYesNoFn(evt: ExpenseClaim): Promise<void> {
  const autoApproveDecision = await DBOS.runStep(async () => autoApprove(evt), {
    name: 'auto_approve',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (autoApproveDecision === true) {
    const payClaimOut = await DBOS.runStep(async () => payClaim(evt), {
      name: 'pay_claim',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
  } else if (autoApproveDecision === false) {
    const fileRefusalOut = await DBOS.runStep(async () => fileRefusal(evt), {
      name: 'file_refusal',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
  } else {
    return;
  }

  const closeClaimOut = await DBOS.runStep(async () => closeClaim(), {
    name: 'close_claim',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const decisionYesNo = DBOS.registerWorkflow(decisionYesNoFn, {
  name: 'decision_yes_no',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'expense.filed',
  idempotencyKeyPath: 'claimId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<ExpenseClaim>;
  const key = event.claimId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'claimId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
