// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/event_trigger.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { parseRequest } from '../../lib/parseRequest.js';
import type { WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function eventTriggerFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const eventTrigger = DBOS.registerWorkflow(eventTriggerFn, {
  name: 'event_trigger',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
  idempotencyKeyPath: 'requestId',
  requesterEmailPath: 'customer.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookEvent>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  const requesterEmail = event.customer?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'customer.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
