// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/for_each.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { confirmSlot } from '../../lib/confirmSlot.js';
import type { Booking, SlotGrid } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function forEachFn(evt: SlotGrid): Promise<void> {
  // allSettled rather than all: one rejection
  // must not take the process down before the
  // others have checkpointed.
  const items = evt.alternatives;
  const settled: PromiseSettledResult<Booking>[] = [];
  for (let offset = 0; offset < items.length; offset += 4) {
    const chunk = items.slice(offset, offset + 4);
    const settledChunk = await Promise.allSettled(
      chunk.map((item, index) =>
        DBOS.runStep(async () => confirmSlot(item), {
          name: `confirm_each[${offset + index}]`,
          retriesAllowed: true,
          maxAttempts: 3,
          intervalSeconds: 1,
          backoffRate: 2,
        }),
      ),
    );
    settled.push(...settledChunk);
  }

  const failed = settled.filter((r) => r.status === 'rejected');
  if (failed.length > 0) {
    throw new Error(
      `confirm_each: ${failed.length} of ${settled.length} items failed`,
    );
  }

  const confirmEachOut = settled.flatMap((r) =>
    r.status === 'fulfilled' ? [r.value] : [],
  );
}

export const forEach = DBOS.registerWorkflow(forEachFn, { name: 'for_each' });

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'slots.found',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
