// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/form_retry.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { recordIntake } from '../../lib/intake.js';
import type { IntakeAnswers, IntakeRequest } from '../../lib/intake.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function formRetryFn(evt: IntakeRequest): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error('form_retry: no workflow id — not running as a workflow.');
  }

  const requesterEmail = evt.contact?.email;

  let round = 0;
  let resume = false;
  let awaitDetailsCarried: IntakeAnswers | undefined;

  do {
    round += 1;

    // A retry can send a second copy when the
    // provider accepted a request whose response
    // was lost. A run that never sends its only
    // link sleeps until its timeout, which is
    // worse.
    await DBOS.runStep(
      async () =>
        sendNodeEmail({
          runId,
          workflowTitle: 'Intake, asked again',
          nodeId: 'ask_details',
          to: requesterEmail,
          subject: 'A few details, please',
          bodyMarkdown: 'We need a little more before we can start.',
          attach: {
            kind: 'form',
            nodeId: 'await_details',
            fields: [
              {
                id: 'name',
                label: 'Your name',
                type: 'text',
                required: true,
                multiple: false,
              },
              {
                id: 'details',
                label: 'What happened?',
                type: 'textarea',
                required: false,
                multiple: false,
              },
            ],
            expiresInSeconds: 86400,
          },
          downstream: ['Record the intake'],
        }),
      {
        name: `ask_details.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
        shouldRetry: isTransientSendFailure,
      },
    );

    await DBOS.runStep(
      async () =>
        registerWaitCorrelation({
          runId,
          nodeId: 'await_details',
          topic: 'form',
          key: 'await_details',
        }),
      {
        name: `await_details.r${round}.register`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    let awaitDetailsResends = 0;
    let awaitDetailsOut: IntakeAnswers | null = null;
    for (;;) {
      // recv answers a timeout with null and
      // never throws, so this is a check and not
      // a catch.
      // 1 day, as seconds.
      awaitDetailsOut = await DBOS.recv<IntakeAnswers>('await_details', {
        timeoutSeconds: 86400,
      });
      if (awaitDetailsOut !== null) break;
      if (awaitDetailsResends >= 2) break;
      awaitDetailsResends += 1;

      await DBOS.runStep(
        async () =>
          sendNodeEmail({
            runId,
            workflowTitle: 'Intake, asked again',
            nodeId: 'ask_details',
            to: requesterEmail,
            subject: 'A few details, please',
            bodyMarkdown: 'We need a little more before we can start.',
            attach: {
              kind: 'form',
              nodeId: 'await_details',
              fields: [
                {
                  id: 'name',
                  label: 'Your name',
                  type: 'text',
                  required: true,
                  multiple: false,
                },
                {
                  id: 'details',
                  label: 'What happened?',
                  type: 'textarea',
                  required: false,
                  multiple: false,
                },
              ],
              expiresInSeconds: 86400,
            },
            downstream: ['Record the intake'],
          }),
        {
          name: `await_details.r${round}.resend.${awaitDetailsResends}`,
          retriesAllowed: true,
          maxAttempts: 3,
          intervalSeconds: 1,
          backoffRate: 2,
          shouldRetry: isTransientSendFailure,
        },
      );
    }

    await DBOS.runStep(
      async () => clearWaitCorrelation(runId, 'await_details'),
      {
        name: `await_details.r${round}.clear`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (awaitDetailsOut === null) {
      throw new Error('await_details: nothing arrived within 1 day.');
    }
    awaitDetailsCarried = awaitDetailsOut;

    if (awaitDetailsOut.complete === false) {
      continue;
    }

    resume = true;
    break;
  } while (round < 3);

  if (!resume) {
    throw new Error('details_ok: more repeated 3 times without a result.');
  }

  if (awaitDetailsCarried === undefined) {
    // Unreachable: every way out of the loop that
    // sets resume has already assigned this. The
    // check is here because the type says so and
    // a cast would be a lie about which of the
    // two is authoritative.
    throw new Error('form_retry: await_details produced no result.');
  }

  const recordIntakeOut = await DBOS.runStep(
    async () => recordIntake(awaitDetailsCarried),
    {
      name: 'record_intake',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const formRetry = DBOS.registerWorkflow(formRetryFn, {
  name: 'form_retry',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'intake.requested',
  requesterEmailPath: 'contact.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<IntakeRequest>;
  const requesterEmail = event.contact?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'contact.email is missing' };
  }
  return { ok: true, key: undefined, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {
  await_details: {
    nodeId: 'await_details',
    title: 'Wait for the details',
    page: 'form',
    fields: [
      {
        id: 'name',
        label: 'Your name',
        type: 'text',
        required: true,
        multiple: false,
      },
      {
        id: 'details',
        label: 'What happened?',
        type: 'textarea',
        required: false,
        multiple: false,
      },
    ],
    downstream: ['Record the intake'],
  },
};

export const eventWaits: EventWait[] = [];
