// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/form_intake.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { recordIntake } from '../../lib/intake.js';
import type { IntakeAnswers, IntakeRequest } from '../../lib/intake.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function formIntakeFn(evt: IntakeRequest): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error('form_intake: no workflow id — not running as a workflow.');
  }

  const requesterEmail = evt.contact?.email;

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Intake form',
        nodeId: 'ask_details',
        to: requesterEmail,
        subject: 'A few details, please',
        bodyMarkdown: 'We need a little more before we can start.',
        attach: {
          kind: 'form',
          nodeId: 'await_details',
          fields: [
            {
              id: 'name',
              label: 'Your name',
              type: 'text',
              required: true,
              multiple: false,
            },
            {
              id: 'urgent',
              label: 'Is this urgent?',
              type: 'yesNo',
              required: false,
              multiple: false,
            },
            {
              id: 'details',
              label: 'What is the rush?',
              type: 'textarea',
              required: false,
              multiple: false,
              showIf: { fieldId: 'urgent', op: 'eq', value: true },
            },
            {
              id: 'photos',
              label: 'Anything to show us?',
              type: 'fileUpload',
              required: false,
              multiple: true,
            },
          ],
          expiresInSeconds: 259200,
        },
        downstream: ['Record the intake'],
      }),
    {
      name: 'ask_details',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );

  await DBOS.runStep(
    async () =>
      registerWaitCorrelation({
        runId,
        nodeId: 'await_details',
        topic: 'form',
        key: 'await_details',
      }),
    {
      name: 'await_details.register',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );

  // recv answers a timeout with null and never
  // throws, so this is a check and not a catch.
  // 3 days, as seconds.
  const awaitDetailsOut = await DBOS.recv<IntakeAnswers>('await_details', {
    timeoutSeconds: 259200,
  });

  await DBOS.runStep(async () => clearWaitCorrelation(runId, 'await_details'), {
    name: 'await_details.clear',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (awaitDetailsOut === null) {
    throw new Error('await_details: nothing arrived within 3 days.');
  }

  const recordIntakeOut = await DBOS.runStep(
    async () => recordIntake(awaitDetailsOut),
    {
      name: 'record_intake',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const formIntake = DBOS.registerWorkflow(formIntakeFn, {
  name: 'form_intake',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'intake.requested',
  idempotencyKeyPath: 'requestId',
  requesterEmailPath: 'contact.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<IntakeRequest>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  const requesterEmail = event.contact?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'contact.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {
  await_details: {
    nodeId: 'await_details',
    title: 'Wait for the details',
    page: 'form',
    fields: [
      {
        id: 'name',
        label: 'Your name',
        type: 'text',
        required: true,
        multiple: false,
      },
      {
        id: 'urgent',
        label: 'Is this urgent?',
        type: 'yesNo',
        required: false,
        multiple: false,
      },
      {
        id: 'details',
        label: 'What is the rush?',
        type: 'textarea',
        required: false,
        multiple: false,
        showIf: { fieldId: 'urgent', op: 'eq', value: true },
      },
      {
        id: 'photos',
        label: 'Anything to show us?',
        type: 'fileUpload',
        required: false,
        multiple: true,
      },
    ],
    downstream: ['Record the intake'],
  },
};

export const eventWaits: EventWait[] = [];
