// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/groom_booking.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { bookAppointment } from '../../lib/bookAppointment.js';
import { findSlot } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import { recordBooking } from '../../lib/recordBooking.js';
import { twilioChat } from '../../lib/twilioChat.js';
import type { ChatReply, SlotGrid, WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';
import { sendNodeEmail } from '../app/mail.js';
import { isTransientSendFailure } from '../app/mailer.js';
import { clearWaitCorrelation, registerWaitCorrelation } from '../app/waits.js';

async function groomBookingFn(evt: WebhookEvent): Promise<void> {
  const runId = DBOS.workflowID;
  if (runId === undefined) {
    throw new Error(
      'groom_booking: no workflow id — not running as a workflow.',
    );
  }

  const requesterEmail = evt.customer?.email;

  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  let round = 0;
  let resume = false;
  let findSlotCarried: SlotGrid | undefined;

  do {
    round += 1;

    const findSlotOut = await DBOS.runStep(
      async () => findSlot(parseRequestOut),
      {
        name: `find_slot.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
    findSlotCarried = findSlotOut;

    if (findSlotOut.requestedSlotFree === true) {
      resume = true;
      break;
    }

    const twilioChatOut = await DBOS.runStep(
      async () => twilioChat(findSlotOut),
      {
        name: `twilio_chat.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    await DBOS.runStep(
      async () =>
        registerWaitCorrelation({
          runId,
          nodeId: 'await_reply',
          topic: 'twilio.reply',
          key: twilioChatOut.to,
        }),
      {
        name: `await_reply.r${round}.register`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    // recv answers a timeout with null and never
    // throws, so this is a check and not a catch.
    // 2 days, as seconds.
    const awaitReplyOut = await DBOS.recv<ChatReply>('await_reply', {
      timeoutSeconds: 172800,
    });

    await DBOS.runStep(async () => clearWaitCorrelation(runId, 'await_reply'), {
      name: `await_reply.r${round}.clear`,
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });

    if (awaitReplyOut === null) {
      throw new Error('await_reply: nothing arrived within 2 days.');
    }

    if (awaitReplyOut.intent === 'reschedule') {
      continue;
    }

    if (awaitReplyOut.intent === 'book') {
      resume = true;
      break;
    }

    return;
  } while (round < 10);

  if (!resume) {
    throw new Error(
      'reply_decision: new_time repeated 10 times without a result.',
    );
  }

  if (findSlotCarried === undefined) {
    // Unreachable: every way out of the loop that
    // sets resume has already assigned this. The
    // check is here because the type says so and
    // a cast would be a lie about which of the
    // two is authoritative.
    throw new Error('groom_booking: find_slot produced no result.');
  }

  const bookAppointmentOut = await DBOS.runStep(
    async () => bookAppointment(findSlotCarried),
    {
      name: 'book_appointment',
      retriesAllowed: true,
      maxAttempts: 2,
      intervalSeconds: 2,
      backoffRate: 2,
    },
  );

  const recordBookingOut = await appDb.runTransaction(
    async () => recordBooking(bookAppointmentOut),
    { name: 'record_booking' },
  );

  // A retry can send a second copy when the
  // provider accepted a request whose response
  // was lost. A run that never sends its only
  // link sleeps until its timeout, which is
  // worse.
  await DBOS.runStep(
    async () =>
      sendNodeEmail({
        runId,
        workflowTitle: 'Groom booking',
        nodeId: 'send_confirmation',
        to: requesterEmail,
        subject: 'Your booking is confirmed',
        bodyMarkdown: '…',
        attach: { kind: 'none' },
        downstream: [],
      }),
    {
      name: 'send_confirmation',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
      shouldRetry: isTransientSendFailure,
    },
  );
}

export const groomBooking = DBOS.registerWorkflow(groomBookingFn, {
  name: 'groom_booking',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
  idempotencyKeyPath: 'requestId',
  requesterEmailPath: 'customer.email',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookEvent>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  const requesterEmail = event.customer?.email;
  if (typeof requesterEmail !== 'string' || requesterEmail === '') {
    return { ok: false, problem: 'customer.email is missing' };
  }
  return { ok: true, key, requesterEmail };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [
  { nodeId: 'await_reply', topic: 'twilio.reply', correlationPath: 'from' },
];
