// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/guarded_chain.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { bookAppointment } from '../../lib/bookAppointment.js';
import { findSlot } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import type { WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function guardedChainFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  if (parseRequestOut.service === 'groom') {
    const findSlotOut = await DBOS.runStep(
      async () => findSlot(parseRequestOut),
      {
        name: 'find_slot',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    const bookAppointmentOut = await DBOS.runStep(
      async () => bookAppointment(findSlotOut),
      {
        name: 'book_appointment',
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
  }
}

export const guardedChain = DBOS.registerWorkflow(guardedChainFn, {
  name: 'guarded_chain',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
