// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/manual_trigger.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { parseRequest } from '../../lib/parseRequest.js';
import type { WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function manualTriggerFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const manualTrigger = DBOS.registerWorkflow(manualTriggerFn, {
  name: 'manual_trigger',
});

export const trigger: TriggerDescriptor = { mode: 'manual' };

export function checkPayload(): PayloadCheck {
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
