// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/parse_request.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { parseRequest as parseRequestHandler } from '../../lib/parseRequest.js';
import type { WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function parseRequestFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(
    async () => parseRequestHandler(evt),
    {
      name: 'parse_request',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const parseRequest = DBOS.registerWorkflow(parseRequestFn, {
  name: 'parse_request',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
