// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/queue_partitioned.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';
import type { WorkflowHandle } from '@dbos-inc/dbos-sdk';

import { indexItem } from '../../lib/indexItem.js';
import type { Batch, Indexed, Item } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  QueueEntry,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { queueKey } from '../app/queues.js';

async function indexItemsQueuedFn(item: Item): Promise<Indexed> {
  return await DBOS.runStep(async () => indexItem(item), {
    name: 'index_items',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

const indexItemsQueued = DBOS.registerWorkflow(indexItemsQueuedFn, {
  name: 'index_items.queued.queue_partitioned',
});

async function queuePartitionedFn(evt: Batch): Promise<void> {
  const items = evt.items;
  const handles: WorkflowHandle<Indexed>[] = [];
  for (const item of items) {
    handles.push(
      await DBOS.startWorkflow(indexItemsQueued, {
        queueName: 'document-index',
        enqueueOptions: {
          queuePartitionKey: queueKey(
            'index_items',
            'customerId',
            item.customerId,
          ),
          priority: 5,
        },
      })(item),
    );
  }

  const settled: PromiseSettledResult<Indexed>[] = [];
  // One at a time rather than through allSettled:
  // one poll loop starts them all, waiting in the
  // order they were enqueued numbers the rows the
  // same way on every run, and the queue holds
  // them back either way.
  for (const handle of handles) {
    try {
      settled.push({ status: 'fulfilled', value: await handle.getResult() });
    } catch (reason) {
      settled.push({ status: 'rejected', reason });
    }
  }

  const failed = settled.filter((r) => r.status === 'rejected');
  if (failed.length > 0) {
    throw new Error(
      `index_items: ${failed.length} of ${settled.length} items failed`,
    );
  }

  const indexItemsOut = settled.flatMap((r) =>
    r.status === 'fulfilled' ? [r.value] : [],
  );
}

export const queuePartitioned = DBOS.registerWorkflow(queuePartitionedFn, {
  name: 'queue_partitioned',
});

export const trigger: TriggerDescriptor = { mode: 'manual' };

export function checkPayload(): PayloadCheck {
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];

export const queues: QueueEntry[] = [
  {
    name: 'document-index',
    options: { workerConcurrency: 4, partitionConcurrency: 2 },
  },
];
