// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/review_loop.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { findSlot } from '../../lib/findSlot.js';
import { readReply } from '../../lib/readReply.js';
import { twilioChat } from '../../lib/twilioChat.js';
import type { BookingReq, ChatPrompt } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function reviewLoopFn(evt: BookingReq): Promise<void> {
  let twilioChatCarried: ChatPrompt | undefined;

  for (let round = 1; round <= 4; round += 1) {
    const findSlotOut = await DBOS.runStep(async () => findSlot(evt), {
      name: `find_slot.r${round}`,
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });

    const twilioChatOut = await DBOS.runStep(
      async () => twilioChat(findSlotOut),
      {
        name: `twilio_chat.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
    twilioChatCarried = twilioChatOut;
  }

  if (twilioChatCarried === undefined) {
    // Unreachable: the loop runs at least once
    // and assigns this. The check is here because
    // the type says so and a cast would be a lie
    // about which of the two is authoritative.
    throw new Error('review_loop: twilio_chat produced no result.');
  }

  const readReplyOut = await DBOS.runStep(
    async () => readReply(twilioChatCarried),
    {
      name: 'read_reply',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const reviewLoop = DBOS.registerWorkflow(reviewLoopFn, {
  name: 'review_loop',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'review.started',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
