// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/schedule_trigger.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { sweepStale } from '../../lib/sweepStale.js';
import type {
  EventWait,
  PayloadCheck,
  ScheduleEntry,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

const SCHEDULE_STARTS = new Date('2026-01-01T00:00:00.000Z');
const SCHEDULE_ENDS = new Date('2026-12-31T23:59:59.000Z');

async function scheduleTriggerFn(
  scheduledTime: Date,
  context: unknown,
): Promise<void> {
  if (scheduledTime < SCHEDULE_STARTS) return;
  if (scheduledTime > SCHEDULE_ENDS) return;

  const sweepStaleOut = await DBOS.runStep(async () => sweepStale(), {
    name: 'sweep_stale',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const scheduleTrigger = DBOS.registerWorkflow(scheduleTriggerFn, {
  name: 'schedule_trigger',
});

export const trigger: TriggerDescriptor = { mode: 'schedule' };

export function checkPayload(): PayloadCheck {
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const schedule: ScheduleEntry = {
  scheduleName: 'schedule_trigger',
  workflowFn: scheduleTrigger,
  schedule: '0 3 * * *',
  cronTimezone: 'Europe/Berlin',
  automaticBackfill: true,
};

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
