// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/slot_retry_continue.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { bookAppointment } from '../../lib/bookAppointment.js';
import { findSlot, tryAgain } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import type { SlotGrid, WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function slotRetryContinueFn(evt: WebhookEvent): Promise<void> {
  const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
    name: 'parse_request',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });

  let round = 0;
  let findSlotCarried: SlotGrid | undefined;

  do {
    round += 1;

    const findSlotOut = await DBOS.runStep(
      async () => findSlot(parseRequestOut),
      {
        name: `find_slot.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );
    findSlotCarried = findSlotOut;

    const lookAgainDecision = await DBOS.runStep(
      async () => tryAgain(findSlotOut),
      {
        name: `look_again.r${round}`,
        retriesAllowed: true,
        maxAttempts: 3,
        intervalSeconds: 1,
        backoffRate: 2,
      },
    );

    if (lookAgainDecision === true) {
      continue;
    }

    if (lookAgainDecision === false) {
      break;
    }

    return;
  } while (round < 10);

  if (findSlotCarried === undefined) {
    // Unreachable: every way out of the loop has
    // already assigned this. The check is here
    // because the type says so and a cast would
    // be a lie about which of the two is
    // authoritative.
    throw new Error('slot_retry_continue: find_slot produced no result.');
  }

  const bookAppointmentOut = await DBOS.runStep(
    async () => bookAppointment(findSlotCarried),
    {
      name: 'book_appointment',
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    },
  );
}

export const slotRetryContinue = DBOS.registerWorkflow(slotRetryContinueFn, {
  name: 'slot_retry_continue',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
  idempotencyKeyPath: 'requestId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookEvent>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
