// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/slot_retry_rechecked.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { findSlot, tryAgain } from '../../lib/findSlot.js';
import { parseRequest } from '../../lib/parseRequest.js';
import { sweepStale } from '../../lib/sweepStale.js';
import type { BookingReq, SlotGrid, WebhookEvent } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';

async function slotRetryRecheckedFn(evt: WebhookEvent): Promise<void> {
  let round = 0;
  let resume = false;
  let parseRequestCarried: BookingReq | undefined;

  do {
    round += 1;

    const parseRequestOut = await DBOS.runStep(async () => parseRequest(evt), {
      name: `parse_request.r${round}`,
      retriesAllowed: true,
      maxAttempts: 3,
      intervalSeconds: 1,
      backoffRate: 2,
    });
    parseRequestCarried = parseRequestOut;

    if ((parseRequestOut.requestedAt?.length ?? 0) > 0) {
      let round2 = 0;
      let findSlotCarried: SlotGrid | undefined;

      do {
        round2 += 1;

        const findSlotOut = await DBOS.runStep(
          async () => findSlot(parseRequestOut),
          {
            name: `find_slot.r${round}.r${round2}`,
            retriesAllowed: true,
            maxAttempts: 3,
            intervalSeconds: 1,
            backoffRate: 2,
          },
        );
        findSlotCarried = findSlotOut;

        const lookAgainDecision = await DBOS.runStep(
          async () => tryAgain(findSlotOut),
          {
            name: `look_again.r${round}.r${round2}`,
            retriesAllowed: true,
            maxAttempts: 3,
            intervalSeconds: 1,
            backoffRate: 2,
          },
        );

        if (lookAgainDecision === true) {
          continue;
        }

        if (lookAgainDecision === false) {
          break;
        }

        return;
      } while (round2 < 10);

      if (findSlotCarried === undefined) {
        // Unreachable: every way out of the loop
        // has already assigned this. The check is
        // here because the type says so and a
        // cast would be a lie about which of the
        // two is authoritative.
        throw new Error('slot_retry_rechecked: find_slot produced no result.');
      }

      if (findSlotCarried.requestedSlotFree === false) {
        continue;
      }

      resume = true;
      break;
    }

    resume = true;
    break;
  } while (round < 5);

  if (!resume) {
    throw new Error('still_ok: start_over repeated 5 times without a result.');
  }

  if (parseRequestCarried === undefined) {
    // Unreachable: every way out of the loop that
    // sets resume has already assigned this. The
    // check is here because the type says so and
    // a cast would be a lie about which of the
    // two is authoritative.
    throw new Error('slot_retry_rechecked: parse_request produced no result.');
  }

  const releaseHoldsOut = await DBOS.runStep(async () => sweepStale(), {
    name: 'release_holds',
    retriesAllowed: true,
    maxAttempts: 3,
    intervalSeconds: 1,
    backoffRate: 2,
  });
}

export const slotRetryRechecked = DBOS.registerWorkflow(slotRetryRecheckedFn, {
  name: 'slot_retry_rechecked',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.requested',
  idempotencyKeyPath: 'requestId',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  const event = payload as Partial<WebhookEvent>;
  const key = event.requestId;
  if (typeof key !== 'string' || key === '') {
    return { ok: false, problem: 'requestId is missing' };
  }
  return { ok: true, key, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
