// GENERATED BY MBOSS — DO NOT EDIT.
// Regenerated from
// .mboss/workflows/transaction.workflow.json.

import { DBOS } from '@dbos-inc/dbos-sdk';

import { recordBooking } from '../../lib/recordBooking.js';
import type { Booking } from '../../lib/types.js';
import type {
  EventWait,
  PayloadCheck,
  TriggerDescriptor,
  WaitDescriptor,
} from '../app/contract.js';
import { appDb } from '../app/db.js';

async function transactionFn(evt: Booking): Promise<void> {
  const recordBookingOut = await appDb.runTransaction(
    async () => recordBooking(evt),
    { name: 'record_booking' },
  );
}

export const transaction = DBOS.registerWorkflow(transactionFn, {
  name: 'transaction',
});

export const trigger: TriggerDescriptor = {
  mode: 'event',
  topic: 'booking.placed',
};

export function checkPayload(payload: unknown): PayloadCheck {
  if (typeof payload !== 'object' || payload === null) {
    return { ok: false, problem: 'the payload is not an object' };
  }
  return { ok: true, key: undefined, requesterEmail: undefined };
}

export const waits: Record<string, WaitDescriptor> = {};

export const eventWaits: EventWait[] = [];
