/**
 * The database the runtime needs, and the config
 * that reaches it.
 *
 * All four of these are byte-compared against
 * mBoss's own copies by a test. That is what stops
 * the type-check gate from ever checking generated
 * code against a Prisma client built from a schema
 * no project actually gets.
 */

/**
 * One model, and it belongs to the runtime rather
 * than to any workflow. Your own models go below
 * it.
 */
export const PRISMA_SCHEMA = `// The application database for this project.
//
// One table, and it belongs to the runtime rather
// than to any workflow: which run is parked on
// which node, so an arriving event or a submitted
// form can find the run that is waiting for it.
// Everything a workflow itself remembers between
// blocks is kept by DBOS, in its own schema.
//
// Your own models go below this one.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  // No url here. Prisma 7 refuses one in this
  // block; the connection string is read from
  // prisma.config.ts instead.
  provider = "postgresql"
}

/// A run waiting on one node, and the topic and
/// key that will wake it. Keyed by run and node
/// rather than by topic and key, because two runs
/// of the same workflow wait on the same node all
/// the time and that is the ordinary case.
///
/// The park column is which occasion of waiting
/// the row is. A wait inside a loop parks on the
/// same node every round, and what wakes a run
/// carries an idempotency key that has to differ
/// between the rounds or the later ones are
/// dropped.
model WaitCorrelation {
  runId  String
  nodeId String
  topic  String
  key    String
  park   String

  @@id([runId, nodeId])
  @@index([topic, key])
  @@map("mboss_wait_correlations")
}
`;

/**
 * Prisma 7 refuses a connection string inside
 * `schema.prisma`, so it lives here. The bracket
 * form on `process.env` is deliberate:
 * `noUncheckedIndexedAccess` is on.
 */
export const PRISMA_CONFIG_TS = `import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
`;

/**
 * The directory name of the one migration a new
 * project ships with. A zero stamp because it is
 * the migration every project starts from — no
 * project's history begins before it, so there is
 * nothing for a real date to order it against.
 */
export const MIGRATION_DIR = '00000000000000_mboss_runtime';

/**
 * Generated by `prisma migrate diff` against the
 * schema above, with one line wrapped to keep the
 * file inside the house width. `migrate deploy`
 * then works against a fresh database without
 * anybody running `migrate dev` first.
 */
export const MIGRATION_SQL = `-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "mboss_wait_correlations" (
    "runId" TEXT NOT NULL,
    "nodeId" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "park" TEXT NOT NULL,

    CONSTRAINT "mboss_wait_correlations_pkey" PRIMARY KEY ("runId","nodeId")
);

-- CreateIndex
CREATE INDEX "mboss_wait_correlations_topic_key_idx"
    ON "mboss_wait_correlations"("topic", "key");
`;

export const MIGRATION_LOCK_TOML = `# Prisma reads only the provider below. Do not
# edit this file by hand, and do commit it.
provider = "postgresql"
`;
